GET http://localhost:3000/genres

###post data
POST http://localhost:3000/genres HTTP/1.1 
content-type: application/json

{
    "name":"Romance",
    "ages":"Teen",
    "aisle":"16"
}


### edit genre
PUT http://localhost:3000/genres/665285f3b496665285f3b4961eff67d571c41eff67d571cc HTTP/1.1 
content-type: application/json

{
    "name":"Mystery",
    "ages":"Children",
    "aisle":"11"
}

### delete genre
DELETE http://localhost:3000/genres/665a5e51d1865067aaec098c HTTP/1.1 
content-type: application/json

### get all employees
GET http://localhost:3000/employees

### post employee
POST http://localhost:3000/Employees HTTP/1.1 
content-type: application/json

{
    "firstName":"Alexis",
    "lastName":"Rose",
    "role":"Cashier",
    "shiftDays":"M,W,TH",
    "shiftStartTime":"9am",
    "shiftEndTime":"4pm",
    "lengthOfEmployment":"6m"
    }

###edit employee
PUT http://localhost:3000/employees/666e151107f4cb8b649408bc HTTP/1.1 
content-type: application/json

{
    "firstName":"Alexis",
    "lastName":"Rose",
    "role":"Cashier",
    "shiftDays":"M,W,F",
    "shiftStartTime":"9am",
    "shiftEndTime":"4pm",
    "lengthOfEmployment":"1y"
    }
###delete employee
DELETE http://localhost:3000/employees/ HTTP/1.1 
content-type: application/json


###Render routes
  GET https://webservices-vqxm.onrender.com/genres
### post data
  POST https://webservices-vqxm.onrender.com/genres HTTP/1.1 
content-type: application/json

{
    "name": "Fantasy",
    "ages": "Adult",
    "aisle": "10"

}
###update data render
  PUT https://webservices-vqxm.onrender.com/genres/665a5e32d1865067aaec098665a5e32d1865067aaec098bb HTTP/1.1 
content-type: application/json

{
    "name": "Mystery",
    "ages": "Adult",
    "aisle": "8"

}


###delete data render
  DELETE https://webservices-vqxm.onrender.com/genres/665a8a47c243181a2f339a02 HTTP/1.1 
content-type: application/json

### get all employees
GET https://webservices-vqxm.onrender.com/employees

### post employee
POST https://webservices-vqxm.onrender.com/employees HTTP/1.1 
content-type: application/json

{
    "firstName":"Stevie",
    "lastName":"Budd",
    "Role":"Cashier",
    "shiftDays":"W,TH,SAT",
    "shiftBeginTime":"4pm",
    "shiftEndTime":"10pm",
    "lengthOfEmployment":"1y"
    }

###edit employee
PUT https://webservices-vqxm.onrender.com/employees HTTP/1.1 
content-type: application/json

{
    "firstName":"Stevie",
    "lastName":"Budd",
    "Role":"Cashier",
    "shiftDays":"W,F,SAT",
    "shiftBeginTime":"3pm",
    "shiftEndTime":"10pm",
    "lengthOfEmployment":"1.5y"
    }
###delete employee
DELETE https://webservices-vqxm.onrender.com/employees/ HTTP/1.1 
content-type: application/json